---
title: "Overview"
author: 
  - name: Florian J. Auer
    url: https://github.com/florian-j-auer
    affiliation: IT-Infrastructure for Translational Medical Research, University of Augsburg
    affiliation_url: https://www.uni-augsburg.de/de/fakultaet/fai/informatik/prof/misit/
date: "03/30/2022"
output: 
  BiocStyle::html_document:
    css: ["custom.css", "bioconductor.css"]
    self_contained: no
    toc: yes
    toc_float: yes
  BiocStyle::pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=55,
                                     args.newline = TRUE,
                                     arrow = TRUE),
                      tidy=TRUE)
```

```{r navigation, eval=HTML, results='asis', echo=FALSE}
res <- knitr::knit_child('navigation/navigation.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```


# Reproducible data integration and visualization of biological networks in R

Here we describe an reproducible workflow for the data integration and visualization of biological networks












```{r navigation2, eval=HTML, results='asis', echo=FALSE}
res <- knitr::knit_child(HTML_file, quiet = TRUE)
cat(res, sep = '\n')
```


